name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version in README.md
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          sed -i "s/Current Version: v[0-9]\+\.[0-9]\+\.[0-9]\+/Current Version: ${VERSION}/" README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update version to ${VERSION}"
          git push

      - name: Create protected.zip
        run: |
          cd protected
          zip -r ../protected.zip .

      - name: Create secure-files.zip
        run: |
          cd secure-files
          zip -r ../secure-files.zip .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            protected.zip
            secure-files.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 